####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/
automation: !include_dir_merge_list automation/

#https://www.home-assistant.io/integrations/generic_ip_camera/
camera:
  - platform: generic
    name: Nursery Camera
    stream_source: !secret stream_source
    still_image_url: !secret still_image_url

#https://www.home-assistant.io/integrations/cloud/
cloud: !include cloud.yaml

#https://home-assistant.io/components/config/
config:

#https://www.home-assistant.io/integrations/counter/
counter:

#https://www.home-assistant.io/components/opengarage/
cover:
  - platform: opengarage
    covers:
      garage:
        name: Garage Door
        host: 192.168.1.18
        device_key: !secret device_key

#https://www.home-assistant.io/integrations/frontend/
frontend:
  themes: !include_dir_merge_named themes/

#https://www.home-assistant.io/integrations/group/
group:
  front_lights:
    entities:
      - switch.kuled6
      - light.yeelight1

#https://www.home-assistant.io/hassio/
hassio:

#https://home-assistant.io/components/history/
history:

#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 244
  unit_system: imperial
  time_zone: !secret time_zone
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24

#https://home-assistant.io/components/http/
http:

#https://www.home-assistant.io/integrations/input_boolean/
input_boolean:

#https://www.home-assistant.io/integrations/input_datetime/
input_datetime:

#https://www.home-assistant.io/integrations/input_number/
input_number:

#https://www.home-assistant.io/integrations/input_select/
input_select:

#https://www.home-assistant.io/integrations/input_text/
input_text:

#https://www.home-assistant.io/integrations/ios/
ios: !include ios.yaml

#https://www.home-assistant.io/integrations/light/
light:
#https://www.home-assistant.io/integrations/flux_led/
  - platform: flux_led
    devices:
      192.168.1.4:
        name: Mikey's Bed Lights
        mode: "rgbw"
      192.168.1.42:
        name: LED Strip Light2
        mode: "rgbw"

#https://www.home-assistant.io/components/light.group/
  - platform: group
    name: Basement Lights
    entities:
      - light.zooz_zen27_s2_dimmer_wall_switch_level
      - light.zooz_zen27_s2_dimmer_wall_switch_level_2
      - light.zooz_zen27_s2_dimmer_wall_switch_level_3

  - platform: group
    name: Bedroom Lights
    entities:
      - light.yeelight3
      - light.yeelight4

#https://home-assistant.io/components/logger/
logger:
  default: warning

#https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:

#https://www.home-assistant.io/integrations/yamaha_musiccast/
media_player:
  - platform: yamaha_musiccast
    host: 192.168.1.3

#https://www.home-assistant.io/integrations/mobile_app/
mobile_app:

#https://home-assistant.io/components/notify.smtp/
notify:
  - platform: smtp
    name: Home_Assistant
    server: smtp.gmail.com
    port: 587
    sender: !secret notification_sender
    starttls: true
    username: !secret notification_username
    password: !secret notification_password
    recipient: !secret notification_recipient

  - platform: smtp
    name: Amy
    server: smtp.gmail.com
    port: 587
    sender: !secret notification_sender
    starttls: true
    username: !secret notification_username
    password: !secret notification_password
    recipient: !secret notification_amy

#https://www.home-assistant.io/integrations/recorder/
recorder:
  purge_keep_days: 7

#https://www.home-assistant.io/integrations/script/
script: !include scripts.yaml

#https://www.home-assistant.io/integrations/sensor/
sensor: !include_dir_merge_list sensors/

#https://www.home-assistant.io/integrations/stream/
stream:

#https://home-assistant.io/components/sun/
sun:

#https://www.home-assistant.io/integrations/switch
switch: !include_dir_merge_list switches/

#https://www.home-assistant.io/integrations/system_health/
system_health:

#https://www.home-assistant.io/integrations/timer/
timer:

#https://www.home-assistant.io/integrations/google_translate/
tts:
  - platform: google_translate

#https://home-assistant.io/components/utility_meter/
utility_meter:
  daily_energy:
    source: sensor.aeon_labs_dsb28_home_energy_meter_2nd_edition_energy
    cycle: daily

  monthly_energy:
    source: sensor.aeon_labs_dsb28_home_energy_meter_2nd_edition_energy
    cycle: monthly

#https://www.home-assistant.io/components/weather.darksky/
weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily

#https://www.home-assistant.io/integrations/zone/
zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 750

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
